---
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://mysql:3306/accountmanager?autoReconnect=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
...